config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'quizzes#index'

  resources :quizzes do
    get 'result'
    get 'play'
  end
  resources :questions

  patch 'quizzes_answer_question', to: 'quizzes#answer_question'

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  title       :string
#  correct     :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  question_id :integer
#

class Answer < ApplicationRecord
  has_many :answer_question
end

app/models/answer_question.rb
# == Schema Information
#
# Table name: answer_questions
#
#  id          :integer          not null, primary key
#  answer_id   :integer
#  question_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_answer_questions_on_answer_id    (answer_id)
#  index_answer_questions_on_question_id  (question_id)
#
# Foreign Keys
#
#  fk_rails_7f56ae34fe  (answer_id => answers.id)
#  fk_rails_8ece0ea7f6  (question_id => questions.id)
#

class AnswerQuestion < ApplicationRecord
  belongs_to :answer
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quiz_id    :integer
#

class Question < ApplicationRecord
  has_many :answers
  has_many :answer_question, through: :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  def check_answer(answer_id)
    answers.where(correct: true, id: answer_id).any?
  end
end

app/models/quiz.rb
# == Schema Information
#
# Table name: quizzes
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Quiz < ApplicationRecord
  has_many :questions
  has_many :answer_questions, through: :questions
  accepts_nested_attributes_for :questions
  accepts_nested_attributes_for :answer_questions
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :answer_question
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!, only: :play
  before_action :all_quiz, only: [:index]
  before_action :find_quiz, only: [:show, :edit, :update, :destroy]

  def new
    @quiz = Quiz.new
    @quiz.questions.build
  end

  def create
    @quiz = Quiz.create(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @quiz_question = @quiz.questions.order("RANDOM()").all
  end

  def play
    @quiz = Quiz.find(params[:quiz_id])
    @quiz_question = @quiz.questions.order("RANDOM()").all
  end

  def result
    @quiz = Quiz.find(params[:quiz_id])
    @cq = @quiz.questions
    @count_correct_answer = 0
    @cq.each do |q|
      if q.answers.where(correct: true).ids[0].to_i == params[quiz_result_path]['answer_question_ids'][0].to_i
        @count_correct_answer += 1
      end
    end
  end

  def update
    @quiz.update_attributes(quiz_params)
    redirect_to @quiz
  end

  def destroy
    @quiz.destroy
    redirect_to @quiz
  end

  def answer_question
    @quiz.update(answer_question_params)
  end

  private

  def answer_question_params
    params.require(:quiz).permit(answer_questions_attributes: %i(question_id answer_id user_id))
    layout :false
  end

  def all_quiz
    @quizzes = Quiz.all
  end

  def find_quiz
    @quiz = Quiz.find(params[:id])
  end

  def quiz_params
    params.require(:quiz).permit(:title, questions_attributes: [:id, :title, :_destroy, answers_attributes: [:id, :title, :correct, :_destroy]])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERT_TYPES = [:error, :info, :success, :warning].freeze unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw('&times;'), :class => 'close', 'data-dismiss' => 'alert') +
                           msg, class: "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title Rails5Contest
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'shared/header'
    = render 'shared/main'
    = render 'shared/footer'

app/views/quizzes/_answer_fields.html.slim
.nested-fields
  br
  = f.input :title
  = f.input :correct

  = link_to_remove_association "remove question", f, class: 'btn btn-outline-danger btn-sm'
  br

app/views/quizzes/_form.html.slim
br
br
h1.text-xs-center Create Quiz 
hr
br

.row
  .col-md-6.offset-md-3
    = simple_form_for @quiz do |f|
      = f.input :title
      
      h3 Questions
      #questions
        = f.simple_fields_for :questions do |question|
          = render 'question_fields', f: question
        .links
          br
          = link_to_add_association 'Add question', f, :questions, class: 'btn btn-outline-primary btn-sm'
          br
          br
      
      = f.button :submit, class: 'btn btn-outline-success'
      
br
br

app/views/quizzes/_question_fields.html.slim
.nested-fields
  br

  = f.input :title

  = link_to_remove_association "remove question", f
  br
  
  h3 Answers
  #answers
    = f.simple_fields_for :answers do |answer|
      = render 'answer_fields', f: answer
    .links
      = link_to_add_association 'Add Answer', f, :answers, class: 'btn btn-outline-primary btn-sm'
    br
    br
    

app/views/quizzes/_quiz.html.slim
br
= link_to quiz.title, quiz_play_path(quiz)

app/views/quizzes/create.html.slim
h1 Quizzes#create
p Find me in app/views/quizzes/create.html.slim

app/views/quizzes/destroy.html.slim
h1 Quizzes#destroy
p Find me in app/views/quizzes/destroy.html.slim

app/views/quizzes/edit.html.slim
= render 'form'

app/views/quizzes/index.html.slim
br
h1.text-xs-center This is Ruby Test Context
hr

br
br

= link_to 'Add Quiz', new_quiz_path, class: 'btn btn-primary'

br
br

= render @quizzes

app/views/quizzes/new.html.slim
= render 'form'

app/views/quizzes/play.html.slim
p 
  strong = @quiz.title

ol
  = simple_form_for "/quizzes/#{@quiz.id}/result", method: :post, html: { "data-id" => "#{@quiz.id}"} do |f|
    - @quiz_question.each do |qq|
      li
        = qq.title
      ul
        = f.simple_fields_for :answered_questions, remote: true do |aq|
          = aq.hidden_field :question_id, value: qq.id
          br
          = aq.hidden_field :user_id, value: current_user.id
          br
          = f.collection_check_boxes :answer_question_ids, qq.answers.order("RANDOM()").all, :id, :title , boolean_style: :inline, item_wrapper_tag: false do |b|
            
          
            = b.label(class: 'btn btn-secondary', style: 'margin-right: 10px; margin-left: 10px;') {b.check_box(data: { remote: true, url: url_for(action: :result ,id: b.object.question_id)}) + b.text }
    br
    = f.button :submit, "Finished", class: 'btn btn-outline-success'

app/views/quizzes/result.html.slim
H1 Result

= @count_correct_answer

app/views/quizzes/show.html.slim
br

/ p 
/   strong = @quiz.title

/ ol
/   = simple_form_for @quiz, url: quizzes_answer_question_path,remote: true do |f|
/     - @quiz_question.each do |qq|
/       li
/         = qq.title
/       ul
/         /= f.collection_radio_buttons "options_#{qq.id}", qq.answers.order("RANDOM()").all.map {|a| [a.title, a.id]}, 
/         /  :first, :last, boolean_style: :inline, item_wrapper_tag: false do |b|
/         = f.collection_check_boxes :answer_question_ids, qq.answers.order("RANDOM()").all.map do |a|
/           = b.text
/           = b.label(class: 'btn btn-secondary', style: 'margin-right: 10px; margin-left: 10px;')
/           - binding.pry
/           = b.radio_button(id: b.object.last, class: 'answer-input')
/     br
/     = f.button :submit, class: 'btn btn-outline-success'

/ ol
/   = simple_form_for @quiz, url :quizzes_answer_question_path, remote: true do |f|
/     - @quiz_question.each do |qq|
/       li = qq.title
/       ul 
/         = f.input :answer, as: :radio_buttons, collection: qq.answers.order("RANDOM()").all.map {|a| [a.title, a.id]}
/     
/     = f.button :submit, class: 'btn btn-outline-success'
/ 
/ ol
/   = form_for @quiz, url: quizzes_answer_question_path do |f|
/     - @quiz.questions.each do |question|
/       li.question
/         = question.title
/         ul
/           = f.fields_for :answer_question do |aq|
/             = aq.hidden_field :question, value: question.id
/             = aq.hidden_field :user, value: current_user.id
/             - question.answers.each do |answer|
/               = aq.radio_button "answer#{answer.id}", answer.id, value: answer.correct
/               = aq.label "answer#{answer.id}", answer.title
/     = f.submit "Answer"

  
/ ol
/   = simple_form_for @quiz, url: quizzes_answer_question_path, remote: true do |f|
/     - @quiz_question.each do |question|
/       li= question.title
/       ul
/         = f.simple_fields_for :answered_questions do |aq|
/           = aq.hidden_field :question, value: question.id
/           = aq.hidden_field :user, value: current_user.id
/ 
/         = f.collection_radio_buttons "options_#{question.id}", question.answers.order("RANDOM()").all.map {|a| [a.title, a.id]}, 
/           :first, :last, boolean_style: :inline, item_wrapper_tag: false do |b|
/             
/           = b.text
/           = b.label(class: 'btn btn-secondary', style: 'margin-right: 10px; margin-left: 10px;')
/           - binding.pry
/           = b.radio_button(id: b.object.last, class: 'answer-input')
/     br
/     = f.button :submit, class: 'btn btn-outline-success'

p 
  strong = @quiz.title

ol
  = simple_form_for @quiz, url: quizzes_pay_path do |f|
    - @quiz_question.each do |qq|
      li
        = qq.title
      ul
        = f.simple_fields_for :answered_questions do |aq|
          = aq.hidden_field :question_id, value: qq.id
          br
          = aq.hidden_field :user_id, value: current_user.id
          br
          = f.collection_check_boxes :answer_question_ids, qq.answers.order("RANDOM()").all.map {|a| [a.id, a.title]}, 
            :first, :last, boolean_style: :inline, item_wrapper_tag: false do |b|
          
            = b.label(class: 'btn btn-secondary', style: 'margin-right: 10px; margin-left: 10px;') {b.check_box(id: b.object.last, class: 'answer-input') + b.text }
    br
    = f.button :submit, class: 'btn btn-outline-success'

app/views/quizzes/update.html.slim
h1 Quizzes#update
p Find me in app/views/quizzes/update.html.slim

app/views/shared/_footer.html.slim
footer.footer
  .container
    p.text-center © 2016 RubyQuiz

app/views/shared/_header.html.slim
header
  nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"
          span.sr-only
          span.icon-bar
          span.icon-bar
          span.icon-bar
        .navbar-brand
          = link_to "RubyQuiz", root_path
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          li= link_to 'ROOT', root_path
        ul.nav.navbar-nav.navbar-right
          li= link_to 'OppS', '#'
          
          li.dropdown
            - if user_signed_in?
              a#drop.dropdown-toggle href='#' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
                span.glyphicon.glyphicon-user
                  = " " + current_user.email + ' '
                  span.caret
              ul.dropdown-menu role='menu' aria-labelledby='drop'
                li= link_to 'Log Out', destroy_user_session_path, :method=>'delete'
                li= link_to 'Edit', edit_user_registration_path
            - else
              li = link_to 'Sign in', new_user_session_path
              li = link_to 'Sign up', new_user_registration_path

app/views/shared/_main.html.slim
.container
  .row
    = bootstrap_flash
    = yield